"""Backend building blocks for the trusted local Text-to-CAD demo."""

from .cad_executor import (
    CAD_EXECUTION_TIMEOUT_SECONDS,
    DEFAULT_OUTPUT_BYTES,
    CADExecutor,
    CancellationToken,
    ExecutionResult,
    build_cad_environment,
    redact_credentials,
)
from .contracts import ToolUseRecord
from .harnesses import (
    AgentHarness,
    AgentRunAdapter,
    AgentRunAdapterRegistry,
    HARNESS_LABELS,
    HarnessUnavailableError,
)
from .events import (
    EVENTS_NAME,
    MAX_EVENT_RESULT_CHARS,
    ProgressEvent,
    ProgressEventError,
    ProgressEventStore,
    ProgressUpdate,
)
from .agent import (
    AGENT_RUN_TIMEOUT_SECONDS,
    AgentConfigurationError,
    AgentRunCancelled,
    AgentRunError,
    AgentRunOutcome,
    AgentRunService,
    AgentSettings,
    MAX_AGENT_RUN_SECONDS,
    MAX_PROVIDER_RETRIES,
    ReferenceGroundedAgent,
    build_chat_model,
    build_deep_agent,
    create_agent_tools,
)
from .model_source import (
    ARTIFACT_DIRECTORY_NAME,
    MODEL_SOURCE_NAME,
    SCENE_ARTIFACT_NAME,
    ModelSourceScaffold,
    create_model_source,
)
from .restricted_tools import AgentModelValidator, RestrictedAgentTools
from .projects import (
    MAX_PROMPT_CHARS,
    Project,
    ProjectError,
    ProjectNotFoundError,
    ProjectState,
    ProjectStateError,
    ProjectStore,
    PromptValidationError,
    RESTART_RECOVERY_REASON,
)
from .pi_sidecar import (
    PI_ABORT_GRACE_SECONDS,
    PI_IMPLEMENTATION_VERSION,
    PI_PROTOCOL_VERSION,
    PiAgentRunService,
    PiProtocolError,
    PiWorkerSupervisor,
)
from .run_coordinator import (
    AgentRunCoordinator,
    RUN_STOP_WAIT_SECONDS,
    RunConflictError,
)
from .scene_validation import SceneParseResult, validate_scene_artifact

__all__ = [
    "ARTIFACT_DIRECTORY_NAME",
    "AGENT_RUN_TIMEOUT_SECONDS",
    "AgentConfigurationError",
    "AgentHarness",
    "AgentRunAdapter",
    "AgentRunAdapterRegistry",
    "AgentRunCancelled",
    "AgentRunError",
    "AgentRunOutcome",
    "AgentRunService",
    "AgentSettings",
    "AgentModelValidator",
    "CAD_EXECUTION_TIMEOUT_SECONDS",
    "CADExecutor",
    "CancellationToken",
    "DEFAULT_OUTPUT_BYTES",
    "ExecutionResult",
    "EVENTS_NAME",
    "MODEL_SOURCE_NAME",
    "ModelSourceScaffold",
    "MAX_PROMPT_CHARS",
    "MAX_AGENT_RUN_SECONDS",
    "MAX_PROVIDER_RETRIES",
    "MAX_EVENT_RESULT_CHARS",
    "HARNESS_LABELS",
    "HarnessUnavailableError",
    "Project",
    "ProjectError",
    "ProjectNotFoundError",
    "ProjectState",
    "ProjectStateError",
    "ProjectStore",
    "PromptValidationError",
    "ProgressEvent",
    "ProgressEventError",
    "ProgressEventStore",
    "ProgressUpdate",
    "RESTART_RECOVERY_REASON",
    "PI_ABORT_GRACE_SECONDS",
    "PI_IMPLEMENTATION_VERSION",
    "PI_PROTOCOL_VERSION",
    "PiAgentRunService",
    "PiProtocolError",
    "PiWorkerSupervisor",
    "ReferenceGroundedAgent",
    "RestrictedAgentTools",
    "SCENE_ARTIFACT_NAME",
    "SceneParseResult",
    "ToolUseRecord",
    "AgentRunCoordinator",
    "RUN_STOP_WAIT_SECONDS",
    "RunConflictError",
    "build_cad_environment",
    "build_chat_model",
    "build_deep_agent",
    "create_model_source",
    "create_agent_tools",
    "redact_credentials",
    "validate_scene_artifact",
]
